### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by akand074** [graphql-python/webob-graphql#2]
Didn't know the best way to ask about this, and there's no contribution docs. Just wondering what's holding up a stable release, there's no issues tracked on this project, have only been working with it for a bit (with graphene) but not having any issues.

Rather not have to explain pinning version `1.0.dev20170404001` in my requirements :smile:

**Comment by syrusakbary** [comment]
A stable version is now in PyPI (1.0)
https://pypi.python.org/pypi/WebOb-GraphQL

:)
